#! /usr/bin/env bash
# SPDX-License-Identifier: MIT

########################################################################
#                                                                      #
#  This file is part a system to setup and control a configuration for #
#  using multiple instances of the rtorrent client.                    #
#                                                                      #
#  Copyright © 2020  Chindraba (Ronald Lamoreaux)                      #
#                    <projects@chindraba.work>                         #
#  - All Rights Reserved                                               #
#                                                                      #
#  Permission is hereby granted, free of charge, to any person         #
#  obtaining a copy of this software and associated documentation      #
#  files (the "Software"), to deal in the Software without             #
#  restriction, including without limitation the rights to use, copy,  #
#  modify, merge, publish, distribute, sublicense, and/or sell copies  #
#  of the Software, and to permit persons to whom the Software is      #
#  furnished to do so, subject to the following conditions:            #
#                                                                      #
#  The above copyright notice and this permission notice shall be      #
#  included in all copies or substantial portions of the Software.     #
#                                                                      #
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,     #
#  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF  #
#  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND               #
#  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS #
#  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN  #
#  ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN   #
#  CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE    #
#  SOFTWARE.                                                           #
#                                                                      #
########################################################################

# The name to use for the controls in systemd
service_name='multi-torrent'

# The directory which will be the root for the system
# Each instance will have a directory in the 'instances'
# sub directory of this directory
torrent_root=~/multi-torrent/

# The local IP address of the machine running rtorrent
internal_ip='192.168.100.2'

# The Internet-facing IP address for the system. Try using
# http://ifconfig.me if you don't know your IP address
external_ip='10.4.4.64'

# The prefix for port numbers used by rtorrent. The system will
# add two more digits to this, so '567' will cause the system to
# use ports in the range 56710 - 56789, if the contents of the 
# included data file are followed
port_range='567'

# vim: syntax=sh ts=4 sw=4 sts=4 et sr
